[package]
name = "my-project"
version = "0.1.0"
authors = ["Anoncomrade993"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vigenere = {git="https://github.com/Anoncomrade993/vigenere"}